---
name: CI

on:
  push:
  pull_request:

  # This is only for testing.
  workflow_dispatch:

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  mason-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install latest stable Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - run: |
          echo "$PWD"
          which nvim
          nvim --version

    # - name: Generate mason docs
    #   run: |
    #     export NVIM_APPNAME=peter.nvim
    #     export XDG_CONFIG_HOME="$PWD"
    #     scripts/gen-mason-docs
    #
    # - name: Verify docs are up-to-date
    #   run: git diff --exit-code
